apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: mrlinhdeptrai9988/client-react
          ports:
            - containerPort: 3000
